/* Shared tokens (mode-agnostic) */

export const sharedTheme = {
  typography: {
    fontFamily: {
      display: '"Geist", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      heading: '"Geist", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      body: '"DM Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      mono: '"JetBrains Mono", ui-monospace, monospace',
    },
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      md: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      xxl: '1.5rem',
      display: 'clamp(2rem, 4.5vw, 3rem)',
      hero: 'clamp(2.75rem, 7vw, 4.5rem)',
      heroDisplay: 'clamp(3.25rem, 9vw, 5.75rem)',
      heroSubtitle: 'clamp(1.125rem, 2.5vw, 1.625rem)',
      sectionIndex: 'clamp(3.5rem, 8vw, 6rem)',
      caption: '0.8rem',
    },
    fontWeight: {
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
    lineHeight: {
      tight: 1.15,
      snug: 1.3,
      normal: 1.625,
      relaxed: 1.75,
    },
    letterSpacing: {
      tight: '-0.03em',
      normal: '-0.01em',
      wide: '0.04em',
      wider: '0.08em',
    },
  },
  spacing: {
    xs: '0.25rem',
    sm: '0.5rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
    xxl: '3rem',
    section: '6rem',
    sectionSm: '4rem',
    sectionLg: '8rem',
    pageX: 'clamp(1.25rem, 4vw, 2.5rem)',
    pageY: 'clamp(2.5rem, 6vw, 4rem)',
  },
  layout: {
    contentMax: '1200px',
    contentWide: '1320px',
    contentNarrow: '960px',
    prose: '42rem',
    proseWide: '52rem',
    heroHeadline: '56rem',
  },
  borderRadius: {
    sm: '6px',
    md: '10px',
    lg: '12px',
    xl: '16px',
    xxl: '20px',
    full: '9999px',
  },
  transitions: {
    fast: '180ms cubic-bezier(0.22, 1, 0.36, 1)',
    normal: '280ms cubic-bezier(0.22, 1, 0.36, 1)',
    slow: '420ms cubic-bezier(0.22, 1, 0.36, 1)',
    theme: '320ms cubic-bezier(0.4, 0, 0.2, 1)',
  },
  motion: {
    easeOut: 'cubic-bezier(0.22, 1, 0.36, 1)',
    easeInOut: 'cubic-bezier(0.45, 0, 0.55, 1)',
    easeSpring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    distance: {
      liftSm: '2px',
      liftMd: '3px',
      liftLg: '4px',
      gridDrift: '12px',
      skipLinkHidden: '200%',
      scrollCue: '6px',
    },
  },
  breakpoints: {
    mobile: '480px',
    tablet: '768px',
    desktop: '1024px',
    wide: '1280px',
    ultraWide: '1600px',
  },
  zIndex: {
    base: 0,
    content: 2,
    dropdown: 100,
    sticky: 200,
    modal: 300,
    toast: 400,
  },
  sizes: {
    icon: {
      sm: '16px',
      md: '40px',
    },
    hamburger: {
      lineWidth: '20px',
      lineHeight: '2px',
      lineGap: '2.5px',
    },
    avatar: {
      hero: '128px',
      heroMobile: '104px',
      heroEditorial: 'min(280px, 42vw)',
      about: '200px',
      aboutMobile: '150px',
    },
    badge: {
      dot: '8px',
      dotSm: '6px',
    },
    bar: {
      accent: '3px',
    },
    button: {
      minHeight: '44px',
      paddingY: '0.8rem',
      paddingX: '1.6rem',
    },
    hero: {
      glowWidth: 'min(85vw, 560px)',
      glowHeight: '280px',
      orbAccent: 'min(200px, 40vw)',
      orbPrimary: 'min(160px, 34vw)',
      gridCell: '36px',
      minHeight: 'min(92vh, 920px)',
      minHeightMobile: '88vh',
      avatarFrame: '360px',
      statMinWidth: '7rem',
      scrollCueHeight: '32px',
      atmosphereWidth: 'min(42vw, 420px)',
      atmosphereHeight: 'min(72vh, 640px)',
    },
    layout: {
      systemBarHeight: '32px',
      headerShellTop: '0',
      headerOffset: '6rem',
      moduleRailWidth: '4.5rem',
      workspaceGap: '1px',
      proseMax: '500px',
    },
    chat: {
      minHeight: '520px',
      messageMaxWidth: '420px',
      messageMaxWidthAdmin: '480px',
    },
    project: {
      previewHeight: '220px',
      previewHeightCompact: '160px',
      previewHeightFeatured: '320px',
    },
  },
};
